- name: Store ZFS encryption key
  ansible.builtin.copy:
    content: "{{ zfs_encryption_key | b64decode }}"
    dest: "{{ encryption.keylocation }}"
    mode: '0600'

- name: Create ZFS pools
  community.general.zpool:
    name: "{{ item.pool_name }}"
    state: present
    force: true
    vdevs: "{{ item.vdevs }}"
    filesystem_properties: "{{ item.filesystem_properties | default({}) }}"
  loop: "{{ zfs_pools }}"
  loop_control:
    label: "{{ item.pool_name }}"

- name: Create ZFS datasets
  community.general.zfs:
    name: "{{ item.dataset_name }}"
    state: present
    extra_zfs_properties:
      encryption: "{{ encryption.encryption }}"
      keyformat: "{{ encryption.keyformat }}"
      keylocation: "file://{{ encryption.keylocation }}"
      compression: "{{ item.compression }}"
      setuid: "{{ item.setuid }}"
      mountpoint: "{{ item.mountpoint }}"
  loop: "{{ datasets }}"
  loop_control:
    label: "{{ item.dataset_name }}"

- name: Ensure ZFS encrypted datasets mount at boot via cron
  ansible.builtin.cron:
    name: "Load ZFS keys and mount datasets at boot"
    user: root
    special_time: reboot
    job: "/usr/sbin/zfs load-key -a && /usr/sbin/zfs mount -a"