---
- name: Create administration group "{{ admin_group[0].name }}"
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid }}"
  with_items:
    - "{{ admin_group }}"
  tags:
    - user_mgmnt

- name: Create sudoers file for group "{{ admin_group[0].name }}"
  ansible.builtin.copy:
    content: "%{{ admin_group[0].name }} ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/{{ admin_group[0].name }}
    mode: "0600"
  tags:
    - user_mgmnt

- name: Users Configuration
  ansible.builtin.include_tasks: user.yml
  with_items:
    - "{{ users }}"
  tags:
    - user_mgmnt
