---
- name: Create users - "{{ item.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    state: "{{ item.state }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.additional_groups }}"
    create_home: true

- name: Update authorized keys - "{{ item.name }}"
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.public_key_path) }}"
    exclusive: true
