---
- name: Create dirs - {{ tools.jellyfin.container_name | upper }}
  ansible.builtin.file:
    state: directory
    path: "{{ tooling_dirs[0].path }}/jellyfin"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0770'

- name: Copy compose - {{ tools.jellyfin.container_name | upper }}
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jellyfin.j2"
    dest: "{{ tooling_dirs[0].path }}/jellyfin/docker-compose.yml"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0750'
  register: compose

- name: Start {{ tools.jellyfin.container_name | upper }}
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/jellyfin"
  changed_when: false

- name: Display container info - {{ tools.jellyfin.container_name | upper }}
  ansible.builtin.include_tasks: "../tests/container_info.yml"
  with_items:
    - name: "{{ tools.jellyfin.container_name }}"
      http_endpoint: http://localhost:8096/web/#/wizardstart.html
  when: not ansible_check_mode
