---
- name: Create Jellyfin dir
  file:
    state: directory
    path: "{{ tooling_dirs[0].path }}/jellyfin"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0770'
- name: Copy Jellyfin docker-compose file
  template:
    src: ../templates/jellyfin.j2
    dest: "{{ tooling_dirs[0].path }}/jellyfin/docker-compose.yml"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0750'
  register: compose
- name: Start Jellyfin container
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/jellyfin"
  when: compose.changed
- name: Get Jellyfin container info
  docker_container_info:
    name: "{{ tools.jellyfin.container_name }}"
  register: result
- name: Print the status of the Jellyfin container
  debug:
    msg: |
      Jellyfin state: {{ result.container['State']['Status'] }}
  when: result.exists
