---
- name: Create Jellyfin dir
  file:
    state: directory
    path: "{{ tooling_dirs[0].path }}/jellyfin"
    owner: "{{ lookup('community.general.bitwarden', 'os_account', field='username')[0] }}"
    group: www-data
    mode: '0770'
- name: Copy Jellyfin docker-compose file
  template:
    src: ../templates/jellyfin.j2
    dest: "{{ tooling_dirs[0].path }}/jellyfin/docker-compose.yml"
    owner: "{{ lookup('community.general.bitwarden', 'os_account', field='username')[0] }}"
    group: www-data
    mode: '0750'
- name: Start Jellyfin container
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/jellyfin"
- name: Get Jellyfin container info
  docker_container_info:
    name: "{{ tools.jellyfin.container_name }}"
  register: result
- name: Print the status of the Jellyfin container
  debug:
    msg: |
      State: {{ result.container['State']['Status'] }}
  when: result.exists
