---
- name: Basic PC configuration
  hosts: all
  gather_facts: false
  collections:
    - community.general
    - ansible.posix
  
  pre_tasks:
    - name: Check connectivity
      action: ping
      tags:
        - pre
        - always

  tasks:
    - name: Import user config tasks
      import_role:
        name: user_mgmnt
