---
- name: Get BW secrets
  block:
    - name: Get OS username
      ansible.builtin.set_fact:
        os_username: "{{ lookup('bitwarden.secrets.lookup', '9a99c8b1-d03c-4c01-8e43-b21801113627') }}"
      no_log: true

    - name: Get Samba password
      ansible.builtin.set_fact:
        samba_password: "{{ lookup('bitwarden.secrets.lookup', '31379641-1ae3-4db6-a356-b218011224cd') }}"
      no_log: true

    - name: Get Cloudflare user
      ansible.builtin.set_fact:
        cloudflare_user: "{{ lookup('bitwarden.secrets.lookup', '9ecb8aef-62b0-4040-9be5-b218010ee7ea') }}"
      no_log: true

    - name: Get Cloudflare API Key
      ansible.builtin.set_fact:
        cloudflare_global_api_key: "{{ lookup('bitwarden.secrets.lookup', '9f9ece58-9542-466c-b949-b218010ebe6e') }}"
      no_log: true

    - name: Get Dynu user
      ansible.builtin.set_fact:
        dynu_username: "{{ lookup('bitwarden.secrets.lookup', '83bc2b4c-24bb-4c39-aa74-b218010f4d76') }}"
      no_log: true

    - name: Get Dynu password
      ansible.builtin.set_fact:
        dynu_password: "{{ lookup('bitwarden.secrets.lookup', 'ffad31ab-3bae-46a1-926b-b218010f372d') }}"
      no_log: true

    - name: Get Dynu email
      ansible.builtin.set_fact:
        dynu_email: "{{ lookup('bitwarden.secrets.lookup', '35f975c2-0f27-405c-a660-b218010f1934') }}"
      no_log: true

    - name: Get Dynu API KEY
      ansible.builtin.set_fact:
        dynu_api_key: "{{ lookup('bitwarden.secrets.lookup', '940d2a61-d6fc-4255-886c-b218010efdc9') }}"
      no_log: true

    - name: Get Nextcloud admin user
      ansible.builtin.set_fact:
        nextcloud_admin_user: "{{ lookup('bitwarden.secrets.lookup', '8b8e6fee-8081-4a06-b493-b218010f9446') }}"
      no_log: true

    - name: Get Nextcloud admin password
      ansible.builtin.set_fact:
        nextcloud_admin_password: "{{ lookup('bitwarden.secrets.lookup', '7a126e4e-c81b-466f-b74d-b218010f8159') }}"
      no_log: true

    - name: Get Nextcloud Mysql root password
      ansible.builtin.set_fact:
        nextcloud_mysql_root_password: "{{ lookup('bitwarden.secrets.lookup', '5b5515c4-c555-492e-a1ac-b218010fb6e2') }}"
      no_log: true

    - name: Get Nextcloud Mysql user
      ansible.builtin.set_fact:
        nextcloud_mysql_user: "{{ lookup('bitwarden.secrets.lookup', '6400c152-865e-41f1-9d6d-b2180110eff9') }}"
      no_log: true

    - name: Get Nextcloud Mysql user password
      ansible.builtin.set_fact:
        nextcloud_mysql_password: "{{ lookup('bitwarden.secrets.lookup', 'e07cdcf4-b567-4f2c-a673-b218010fc836') }}"
      no_log: true

    - name: Get Grafana username
      ansible.builtin.set_fact:
        grafana_username: "{{ lookup('bitwarden.secrets.lookup', 'f07e7087-206c-4405-a837-b2ba0089b915') }}"
      no_log: true

    - name: Get Grafana password
      ansible.builtin.set_fact:
        grafana_password: "{{ lookup('bitwarden.secrets.lookup', '4656ac8f-0897-48d7-bac2-b2ba0089dad0') }}"
      no_log: true