- name: Get Doppler secrets
  ansible.builtin.set_fact:
    "{{ item.variable_name }}": "{{ lookup(
      'dcostakos.doppler.doppler_secrets',
      project=doppler_vault.project_name,
      token=lookup('env', 'DOPPLER_SERVICE_TOKEN'),
      config=doppler_vault.config,
      name=item.secret_name
    ) }}"
  loop: "{{ doppler_vault.secrets }}"
