---
- name: Base config
  hosts: all:!localhost

  pre_tasks:
    - name: Check connectivity
      action: ansible.builtin.ping
      tags:
        - pre
        - always

  vars:
    ARGOCD_SSH_PRIVATE_KEY: "{{ lookup('file', '~/.ssh/argocd-repo-key') }}"

  tasks:
    - name: Import user_mgmnt role
      ansible.builtin.import_role:
        name: user_mgmnt
      tags:
        - user_mgmnt
        - user
    - name: Import os_mgmnt role
      ansible.builtin.import_role:
        name: os_mgmnt
      tags:
        - os_mgmnt
        - os
    # - name: Import zfs_setup role
    #   ansible.builtin.import_role:
    #     name: zfs
    #   tags:
    #     - zfs
    #     - storage
    - name: Import K3s role
      ansible.builtin.import_role:
        name: k3s
      when: k3s.deploy
      tags:
        - k3s
    - name: Import ARGOCD role
      ansible.builtin.import_role:
        name: argo_cd
      when: k3s.argocd.deploy
      tags:
        - argo
        - argocd
    # - name: Import reboot role
    #   ansible.builtin.import_role:
    #     name: reboot
    #   tags:
    #     - reboot
