---
- name: Base config
  hosts: all:!localhost
  gather_facts: false
  become: true

  pre_tasks:
    - name: Import Vault secrets
      ansible.builtin.import_tasks: import_vault_data.yml
      tags:
        - pre
        - always
    - name: Check connectivity
      action: ansible.builtin.ping
      tags:
        - pre
        - always

  tasks:
    - name: Import user_mgmnt role
      ansible.builtin.import_role:
        name: user_mgmnt
      tags:
        - user_mgmnt
    - name: Import os_mgmnt role
      ansible.builtin.import_role:
        name: os_mgmnt
      tags:
        - os_mgmnt
    - name: Import ddns_update role
      ansible.builtin.import_role:
        name: ddns
      tags:
        - ddns
    - name: Import zfs_setup role
      ansible.builtin.import_role:
        name: zfs
      tags:
        - zfs
        - storage
    - name: Import Git Checkout role
      ansible.builtin.import_role:
        name: checkout_compose_repo
      tags:
        - git
        - compose_repo
    - name: Import K3s role
      ansible.builtin.import_role:
        name: k3s
      tags:
        - k3s
      when: k3s.deploy
    - name: Import ARGOCD role
      ansible.builtin.import_role:
        name: argo_cd
      when: k3s.argocd.deploy
      tags:
        - argo
        - argocd
    - name: Import reboot role
      ansible.builtin.import_role:
        name: reboot
      tags:
        - reboot
