---
- name: Base config
  hosts: all:!localhost

  pre_tasks:
    - name: Check connectivity
      action: ansible.builtin.ping
      tags:
        - pre
        - always

  vars:
    ARGOCD_SSH_PRIVATE_KEY: "{{ lookup('bitwarden.secrets.lookup', '724cbb4e-5819-4922-908a-b44b0146bbb4') }}"
    ARGOCD_SSH_PUBLIC_KEY: "{{ lookup('bitwarden.secrets.lookup', 'c6d600a3-33e4-4be8-b05d-b44b0146d65d') }}"
    ARGOCD_ADMIN_PASS: "{{ lookup('bitwarden.secrets.lookup', '3159c97d-b90b-462c-ad9d-b44b01460344') }}"
    CLOUDFLARE_API_TOKEN: "{{ lookup('bitwarden.secrets.lookup', '1abe2ffd-03da-4703-b2c3-b44b0145e635') }}"
    WYGIWYH_SECRET_KEY: "{{ lookup('bitwarden.secrets.lookup', 'f429492a-8eb7-4337-bc4a-b4800149ec0c') }}"
    WYGIWYH_SQL_PASSWORD: "{{ lookup('bitwarden.secrets.lookup', '9f2b3871-e676-4c7b-ad0c-b480014a03bf') }}"
    SAMBA_PASSWORD_PRZEMEK: "{{ lookup('bitwarden.secrets.lookup', '33468bae-8840-465b-a9a7-b44b01461568') }}"
    ZFS_ENCRYPTION_KEY: "{{ lookup('bitwarden.secrets.lookup', '1b5bf94a-d9a4-4f6d-94ed-b3ee00ce2132') }}"

  tasks:
    - name: Import user_mgmnt role
      ansible.builtin.import_role:
        name: user_mgmnt
      tags:
        - user_mgmnt
        - user
    - name: Import os_mgmnt role
      ansible.builtin.import_role:
        name: os_mgmnt
      tags:
        - os_mgmnt
        - os
    - name: Import zfs_setup role
      ansible.builtin.import_role:
        name: zfs
      tags:
        - zfs
        - storage
    - name: Import Samba role
      ansible.builtin.import_role:
        name: samba
      tags:
        - samba
    - name: Import K3s role
      ansible.builtin.import_role:
        name: k3s
      when: k3s.deploy
      tags:
        - k3s
    - name: Import ARGOCD role
      ansible.builtin.import_role:
        name: argo_cd
      when: k3s.argocd.deploy
      tags:
        - argo
        - argocd
    # - name: Import reboot role
    #   ansible.builtin.import_role:
    #     name: reboot
    #   tags:
    #     - reboot
