---
- name: Base config
  hosts: all:!localhost
  gather_facts: true
  become: true

  pre_tasks:
    - name: Check connectivity
      action: ansible.builtin.ping
      tags:
        - pre
        - always

  vars:
    ZFS_ENCRYPTION_KEY: "{{ lookup('bitwarden.secrets.lookup', '1b5bf94a-d9a4-4f6d-94ed-b3ee00ce2132') }}"
    SRV_PRIVATE_KEY: "{{ lookup('bitwarden.secrets.lookup', 'f6519533-aa58-49be-b550-b3ee00ce5481') }}"
    SRV_PUBLIC_KEY: "{{ lookup('bitwarden.secrets.lookup', '38f9b44f-c56e-49a1-b905-b3ee00ce6f75') }}"
    BWS_ACCESS_TOKEN: "{{ lookup('bitwarden.secrets.lookup', 'cfbccbd3-a6dd-4ed0-8fe5-b3ee00d60aea') }}"

  tasks:
    - name: Import user_mgmnt role
      ansible.builtin.import_role:
        name: user_mgmnt
      tags:
        - user_mgmnt
    - name: Import os_mgmnt role
      ansible.builtin.import_role:
        name: os_mgmnt
      tags:
        - os_mgmnt
    - name: Import zfs_setup role
      ansible.builtin.import_role:
        name: zfs
      tags:
        - zfs
        - storage
    - name: Import Docker Compose role
      ansible.builtin.import_role:
        name: checkout_compose_repo
      when: composestack.deploy
      tags:
        - git
        - compose_repo
    - name: Import K3s role
      ansible.builtin.import_role:
        name: k3s
      when: k3s.deploy
      tags:
        - k3s
    - name: Import ARGOCD role
      ansible.builtin.import_role:
        name: argo_cd
      when: k3s.argocd.deploy
      tags:
        - argo
        - argocd
    # - name: Import reboot role
    #   ansible.builtin.import_role:
    #     name: reboot
    #   tags:
    #     - reboot
