---
- name: Software stack configuration
  hosts: nas
  gather_facts: true
  collections:
    - community.general
    - ansible.posix

  pre_tasks:
    - name: Check connectivity
      action: ping
      tags:
        - pre
        - always

  tasks:
    - name: Import user_mgmnt role
      import_role:
        name: samba
      tags:
        - samba
    - name: Tools configuration
      block:
        - name: Create docker network - "{{ tools.docker.network.name }}"
          docker_network:
            name: "{{ tools.docker.network.name }}"
        - name: Create tools dirs
          file:
            state: directory
            path: "{{ item.path }}"
            owner: "{{ lookup('community.general.bitwarden', 'os_account', field='username')[0] }}"
            group: www-data
            mode: "{{ item.chmod }}"
          with_items: "{{ tooling_dirs }}"
        - name: Import jellyfin role
          import_role:
            name: jellyfin
          tags: jellyfin
        - name: Import Nextcloud role
          import_role:
            name: nextcloud
          tags: nextcloud
        - name: Import Traefik role
          import_role:
            name: traefik
          tags: traefik
        - name: Import ddns role
          import_role:
            name: ddns
          tags: ddns
      tags:
        - tools
