---
- name: Software stack configuration
  hosts: nas
  gather_facts: false
  collections:
    - community.general
    - ansible.posix

  pre_tasks:
    - name: Import Bitwarden secrets
      ansible.builtin.import_tasks: import_vault_data.yml
      tags:
        - pre
        - always
    - name: Check connectivity
      action: ping
      tags:
        - pre
        - always

  tasks:
    - name: Import samba role
      import_role:
        name: samba
      tags:
        - samba
    - name: Enable disks backup
      ansible.builtin.cron:
        name: "RSYNC samba shares"
        minute: "0"
        hour: "5"
        user: root
        job: "rsync -az --delete --exclude 'filmy' {{ samba_shares_partition[0].path }} {{ samba_backup_partition[0].path }}/samba_shares_backup/"
      tags:
        - samba_backup
    - name: Tools configuration
      block:
        - name: Create docker network - "{{ tools.docker.network.name }}"
          docker_network:
            name: "{{ tools.docker.network.name }}"
        - name: Create tool dirs
          file:
            state: directory
            path: "{{ item.path }}"
            owner: "{{ os_username }}"
            group: "{{ item.group }}"
            mode: "{{ item.chmod }}"
          with_items: "{{ tooling_dirs }}"
        - name: Import Jellyfin role
          import_role:
            name: jellyfin
          tags: jellyfin
        - name: Import Nextcloud role
          import_role:
            name: nextcloud
          tags: nextcloud
        - name: Import Traefik role
          import_role:
            name: traefik
          tags: traefik
        - name: Import DDNS role
          import_role:
            name: ddns
          tags: ddns
      tags:
        - tools
