---
- name: Software stack configuration
  hosts: "{{ variable_host | default('nas') }}"
  gather_facts: false

  pre_tasks:
    - name: Import Bitwarden secrets
      ansible.builtin.import_tasks: import_vault_data.yml
      tags:
        - pre
        - always
    - name: Check connectivity
      action: ansible.builtin.ping
      tags:
        - pre
        - always

  tasks:
    - name: Import samba role
      ansible.builtin.import_role:
        name: samba
      tags:
        - samba_config
    - name: Enable disks backup
      ansible.builtin.cron:
        name: "RSYNC samba shares"
        minute: "0"
        hour: "5"
        user: root
        job: "rsync -az --delete --exclude 'filmy' {{ samba_shares_partition[0].path }}/ {{ samba_backup_partition[0].path }}/samba_shares_backup/"
      tags:
        - samba_backup
    - name: Tools configuration
      tags:
        - tools
      block:
        - name: Create docker network - "{{ tools.docker.network.name }}"
          community.docker.docker_network:
            name: "{{ tools.docker.network.name }}"
            ipam_config:
              - subnet: "{{ tools.docker.network.subnet }}"
                gateway: "{{ tools.docker.network.gateway }}"
          tags:
            - docker_network
        - name: Create tool dirs
          ansible.builtin.file:
            state: directory
            path: "{{ item.path }}"
            owner: "{{ os_username }}"
            group: "{{ item.group }}"
            mode: "{{ item.chmod }}"
          with_items: "{{ tooling_dirs }}"
        - name: Import Traefik role
          ansible.builtin.import_role:
            name: traefik
          tags: traefik
        - name: Import Home_Assistant role
          ansible.builtin.import_role:
            name: home_assistant
          tags: home_assistant
        - name: Import Nextcloud role
          ansible.builtin.import_role:
            name: nextcloud
          tags: nextcloud
        - name: Import Jellyfin role
          ansible.builtin.import_role:
            name: jellyfin
          tags: jellyfin
        - name: Import DDNS role
          ansible.builtin.import_role:
            name: ddns
          tags: ddns
