---
- name: Basic PC configuration
  hosts: localhost
  gather_facts: true
  collections:
    - community.general
    - ansible.posix
  
  pre_tasks:
    - name: Check connectivity
      action: ping
      tags:
        - pre
        - always

  tasks:
    - name: Import user config tasks
      import_role:
        name: user_mgmnt
    # - name: Import OS mgmnt role
    #   import_role:
    #     name: system_mgmnt 

