---
- name: Maintenance
  hosts: "{{ variable_host | default('all') }}"
  gather_facts: false

  pre_tasks:
    - name: Import Bitwarden secrets
      ansible.builtin.import_tasks: import_vault_data.yml
      tags:
        - pre
        - always
    - name: Check connectivity
      action: ansible.builtin.ping
      tags:
        - pre
        - always

  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
        autoremove: true
        purge: true
    - name: Cleanup Journalctl log
      ansible.builtin.shell: |
        journalctl --vacuum-time=2d
      changed_when: false
    - name: Prune dangling docker objects
      community.docker.docker_prune:
        images: true
