---
- name: Base config
  hosts: all:!localhost
  gather_facts: false
  become: true

  pre_tasks:
    # - name: Import Bitwarden secrets
    #   ansible.builtin.import_tasks: import_vault_data.yml
    #   tags:
    #     - pre
    #     - always
    - name: Check connectivity
      action: ansible.builtin.ping
      tags:
        - pre
        - always

  tasks:
    # - name: Import user_mgmnt role
    #   ansible.builtin.import_role:
    #     name: user_mgmnt
    #   tags:
    #     - user_mgmnt
    # - name: Import os_mgmnt role
    #   ansible.builtin.import_role:
    #     name: os_mgmnt
    #   tags:
    #     - os_mgmnt
    - name: Import zfs_setup role
      ansible.builtin.import_role:
        name: zfs
      tags:
        - zfs
    - name: Import reboot role
      ansible.builtin.import_role:
        name: reboot
      tags:
        - reboot
