---
collections:
  - name: community.general
    src: https://galaxy.ansible.com
  - name: community.docker
    src: https://galaxy.ansible.com
  - name: ansible.posix
    src: https://galaxy.ansible.com
  - name: dcostakos.doppler
    src: git+https://github.com/dcostakos/doppler.git,stable-1.0.1
