---
- name: Install Samba packages
  apt:
    name: "{{ packages }}"
    state: present
  tags:
    - samba

- name: Create Samba dirs
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: "{{ item.chmod }}"
  with_items:
    - "{{ samba_shares_partition }}"
    - "{{ samba_backup_partition }}"
  tags:
    - samba

- name: Mount Drives
  block:
    - name: Mount Drives
      mount:
        path: "{{ item.path }}"
        src: "UUID={{ item.uuid }}"
        state: mounted
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
      with_items:
        - "{{ samba_shares_partition }}"
        - "{{ samba_backup_partition }}"
  tags:
    - samba

- name: Setup SMB config
  block:
    - name: Copy Samba config file
      template:
        src: ../templates/smb.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: "{{ admin_group[0].name }}"
        mode: '0660'
      register: config_copy

    - name: Update samba password
      shell: |
        echo "{{ samba_password}}
        {{ samba_password }}" |
        smbpasswd -a {{ os_username }}
      tags:
        - password

    - name: Restart samba
      service:
        name: smbd
        state: restarted
      when: config_copy.changed
  tags:
    - samba
