---
- name: Install Samba packages
  ansible.builtin.apt:
    name: "{{ samba_packages }}"
    state: present
  tags:
    - samba

- name: Create Samba dirs
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: "{{ item.chmod }}"
  with_items:
    - "{{ samba_shares_partition }}"
    - "{{ samba_backup_partition }}"
  tags:
    - samba

- name: Mount Drives
  tags:
    - samba
  block:
    - name: Mount Drives
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "UUID={{ item.uuid }}"
        state: mounted
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
      with_items:
        - "{{ samba_shares_partition }}"
        - "{{ samba_backup_partition }}"

- name: Setup SMB config
  tags:
    - samba
  block:
    - name: Copy Samba config file
      ansible.builtin.template:
        src: "{{ playbook_dir }}/roles/samba/templates/smb.j2"
        dest: /etc/samba/smb.conf
        owner: root
        group: "{{ admin_group[0].name }}"
        mode: '0660'
      notify: Restart samba

    - name: Update samba password
      ansible.builtin.shell: |
        set -o pipefail
        echo "{{ samba_password }}
        {{ samba_password }}" |
        smbpasswd -a {{ os_username }}
      args:
        executable: /bin/bash
      changed_when: false
      tags:
        - password

    - name: Flush handlers    # Triggers handlers instantly
      ansible.builtin.meta: flush_handlers
