- name: Create /etc/samba directory
  ansible.builtin.file:
    path: /etc/samba
    state: directory
    mode: '0755'

- name: Deploy smb.conf
  ansible.builtin.copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'

- name: Run Samba container
  community.docker.docker_container:
    name: samba
    image: dockurr/samba:4.23.5
    state: started
    restart_policy: always
    hostname: samba.local
    network_mode: host
    env:
      TZ: Europe/Warsaw
      USER: "przemek"
      PASS: "{{ SAMBA_PASSWORD_PRZEMEK }}"
      PUID: "0"
      PGID: "0"
    ports:
      - 445:445
    volumes:
      - /data/public:/share/public
      - /data/priv:/share/priv
      - /etc/samba/smb.conf:/etc/samba/smb.conf
