- name: Create samba stack directory
  ansible.builtin.file:
    path: /opt/stacks/samba
    state: directory
    mode: '0755'

- name: Deploy smb.conf
  ansible.builtin.copy:
    src: smb.conf
    dest: /opt/stacks/samba/smb.conf
    owner: root
    group: root
    mode: '0644'

- name: Deploy compose file
  ansible.builtin.copy:
    src: compose.yml
    dest: /opt/stacks/samba/compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Run Samba via Docker Compose
  ansible.builtin.shell:
    cmd: docker compose up -d --remove-orphans
    chdir: /opt/stacks/samba
  environment:
    SAMBA_PASSWORD_PRZEMEK: "{{ SAMBA_PASSWORD_PRZEMEK }}"
  no_log: true
