- name: Install Helm via get_helm.sh script
  tags:
    - helm
  block:
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'
        force: no
    - name: Execute Helm install script
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

# -----------------------------------------
# ArgoCD Namespace and Secrets Setup
# -----------------------------------------

- name: Create ArgoCD namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ k3s.argocd.namespace }}"
  environment:
    KUBECONFIG: "{{ k3s.kubeconfig_file }}"

- name: Create ArgoCD SSH repo credentials secret
  kubernetes.core.k8s:
    state: present
    namespace: "{{ k3s.argocd.namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-apps-ssh-private-key
        namespace: "{{ k3s.argocd.namespace }}"
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      stringData:
        type: git
        url: git@github.com:przemekgorzynski/ArgoCDApps.git
        sshPrivateKey: "{{ ARGOCD_SSH_PRIVATE_KEY }}"
  environment:
    KUBECONFIG: "{{ k3s.kubeconfig_file }}"
  no_log: true

- name: Install ArgoCD with Helm
  block:
    - name: Ensure temporary directory for ArgoCD values
      ansible.builtin.file:
        path: /argocd_values
        state: directory
        mode: '0755'

    - name: Copy ArgoCD values file
      ansible.builtin.copy:
        src: ArgoCD_config.yml
        dest: /argocd_values/values.yaml
        mode: '0644'

    - name: Install/upgrade ArgoCD using Helm
      ansible.builtin.shell: |
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update

        helm upgrade --install argocd argo/argo-cd \
          --namespace "{{ k3s.argocd.namespace }}" \
          --values /argocd_values/values.yaml
      environment:
        KUBECONFIG: "{{ k3s.kubeconfig_file }}"
      args:
        executable: /bin/bash
      become: false

# -----------------------------------------
# ArgoCD Admin Password Secret
# -----------------------------------------

- name: Set ArgoCD admin password secret
  kubernetes.core.k8s:
    state: present
    namespace: "{{ k3s.argocd.namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
        namespace: "{{ k3s.argocd.namespace }}"
        labels:
          app.kubernetes.io/name: argocd-secret
          app.kubernetes.io/part-of: argocd
      stringData:
        admin.password: "{{ ARGOCD_ADMIN_PASS }}"
        admin.passwordMtime: "{{ ansible_date_time.iso8601 }}"
  environment:
    KUBECONFIG: "{{ k3s.kubeconfig_file }}"
  no_log: true

# -----------------------------------------
# Cloudflare Secret for cert-manager
# -----------------------------------------

- name: Create cert-manager namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
  environment:
    KUBECONFIG: "{{ k3s.kubeconfig_file }}"

- name: Create Cloudflare API token secret for cert-manager
  kubernetes.core.k8s:
    state: present
    namespace: cert-manager
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token
        namespace: cert-manager
      type: Opaque
      stringData:
        api-token: "{{ CLOUDFLARE_API_TOKEN }}"
  environment:
    KUBECONFIG: "{{ k3s.kubeconfig_file }}"
  no_log: true

# -----------------------------------------
# ArgoCD App of apps
# -----------------------------------------

- name: Deploy Argo config
  block:
    - name: Copy Argo manifest to temp location
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/argocd_values/{{ item | basename }}"
        mode: '0644'
      loop:
        - "{{ role_path }}/files/App_of_apps.yml"
    - name: Apply Argo manifest
      kubernetes.core.k8s:
        kubeconfig: "{{ k3s.kubeconfig_file }}"
        state: present
        src: "{{ item }}"
      loop:
        - "/argocd_values/App_of_apps.yml"

