---
- name: Create Nextcloud dirs
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.chmod }}"
  with_items:
    - path: "{{ tooling_dirs[0].path }}/nextcloud"
      owner: "{{ lookup('community.general.bitwarden', 'os_account', field='username')[0] }}"
      group: www-data
      chmod: '0770'
- name: Copy Nextcloud config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.chmod }}"
  with_items:
    - src: ../templates/nextcloud.j2
      dest: "{{ tooling_dirs[0].path }}/nextcloud/docker-compose.yml"
      owner: "{{ lookup('community.general.bitwarden', 'os_account', field='username')[0] }}"
      group: www-data
      chmod: '0750'
- name: Start Nextcloud container
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/nextcloud"
- name: Get Nextcloud container info
  docker_container_info:
    name: "{{ tools.nextcloud.app.container_name }}"
  register: result
- name: Print the status of the Nextcloud container
  debug:
    msg: |
      State: {{ result.container['State']['Status'] }}
  when: result.exists
