---
- name: Create Nextcloud dir
  file:
    state: directory
    path: "{{ tooling_dirs[0].path }}/nextcloud"
    owner: "{{ lookup('community.general.bitwarden', 'os_account', field='username')[0] }}"
    group: www-data
    mode: '0770'
- name: Copy Nextcloud docker-compose file
  template:
    src: ../templates/nextcloud.j2
    dest: "{{ tooling_dirs[0].path }}/nextcloud/docker-compose.yml"
    owner: "{{ lookup('community.general.bitwarden', 'os_account', field='username')[0] }}"
    group: www-data
    mode: '0750'
- name: Start Nextcloud container
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/nextcloud"
- name: Get Nextcloud container info
  docker_container_info:
    name: "{{ tools.nextcloud.app.container_name }}"
  register: result
- name: Print the status of the Nextcloud container
  debug:
    msg: |
      State: {{ result.container['State']['Status'] }}
  when: result.exists
