---
- name: Create dirs - {{ tools.nextcloud.app.container_name | upper }}
  ansible.builtin.file:
    state: directory
    path: "{{ tooling_dirs[0].path }}/nextcloud"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0770'

- name: Copy compose - {{ tools.nextcloud.app.container_name | upper }}
  ansible.builtin.template:
    src: "{{ role_path }}/templates/nextcloud.j2"
    dest: "{{ tooling_dirs[0].path }}/nextcloud/docker-compose.yml"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0750'
  register: compose

- name: Start {{ tools.nextcloud.app.container_name | upper }}
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/nextcloud"
  changed_when: false

- name: Display container info - {{ tools.nextcloud.app.container_name | upper }}
  ansible.builtin.include_tasks: ../tests/container_info.yml
  with_items:
    - name: "{{ tools.nextcloud.app.container_name }}"
      http_endpoint: http://localhost:4000
    - name: "{{ tools.nextcloud.db.container_name }}"
  when: not ansible_check_mode
