---
- name: Create Nextcloud dirs
  file:
    state: directory
    path: "{{ tooling_dirs[0].path }}/nextcloud"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0770'
- name: Copy Nextcloud config file
  template:
    src: ../templates/nextcloud.j2
    dest: "{{ tooling_dirs[0].path }}/nextcloud/docker-compose.yml"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0750'
  register: compose
- name: Start Nextcloud container
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/nextcloud"
  when: compose.changed
- name: Get Nextcloud container info
  docker_container_info:
    name: "{{ tools.nextcloud.app.container_name }}"
  register: result
- name: Print the status of the Nextcloud container
  debug:
    msg: |
      Nextcloud state: {{ result.container['State']['Status'] }}
  when: result.exists
