---
- name: Create {{ tools.nextcloud.app.container_name | upper }} dirs
  file:
    state: directory
    path: "{{ tooling_dirs[0].path }}/nextcloud"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0770'

- name: Copy {{ tools.nextcloud.app.container_name | upper }} docker-compose file
  template:
    src: ../templates/nextcloud.j2
    dest: "{{ tooling_dirs[0].path }}/nextcloud/docker-compose.yml"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0750'
  register: compose

- name: Start {{ tools.nextcloud.app.container_name | upper }}
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/nextcloud"
  when: compose.changed

- name: Display {{ tools.nextcloud.app.container_name | upper }} container info
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tests/container_info.yml"
  with_items:
    - name: "{{ tools.nextcloud.app.container_name }}"
      http_endpoint: http://localhost:4000
    - name: "{{ tools.nextcloud.db.container_name }}"
