---
- name: Set repo name variable
  ansible.builtin.set_fact:
    repo_name: "{{ tools.monitoring.repository.split('/')[4].split('.')[0] }}"

- name: Create destination directory
  ansible.builtin.file:
    path: "{{ tools.monitoring.repo_path }}"
    state: directory
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0770'

- name: Checkout monitoring repository
  ansible.builtin.git:
    force: true
    repo: "{{ tools.monitoring.repository }}"
    dest: "{{ tools.monitoring.repo_path }}/{{ repo_name }}"
    version: "{{ tools.monitoring.branch }}"

- name: Deploy config from template
  ansible.builtin.template:
    src: "{{ role_path }}/templates/docker-compose.j2"
    dest: "{{ tools.monitoring.repo_path }}/{{ repo_name }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
  when: tools.monitoring.expose

- name: Start monitoring stack
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: "{{ tools.monitoring.repo_path }}/{{ repo_name }}"
  changed_when: false
