---
- name: Create NFS dir
  ansible.builtin.file:
    state: directory
    path: "{{ nfs_config.nfs_share }}"
    owner: nobody
    group: nogroup
    mode: "{{ nfs_config.nfs_share_chmod }}"

- name: Copy NFS config file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/nfs/templates/exports.j2"
    dest: "{{ nfs_config.config_file }}"
    owner: root
    group: "{{ admin_group[0].name }}"
    mode: '0660'
  notify: Restart nfs

- name: Install NFS packages
  ansible.builtin.apt:
    name: "{{ nfs_packages }}"
    state: present

- name: Export NFS shares
  command: exportfs -ra

- name: Ensure both domains are set under [General] in /etc/idmapd.conf
  blockinfile:
    path: /etc/idmapd.conf
    marker: "# {mark} ANSIBLE MANAGED NFS DOMAIN BLOCK"
    block: |
      Domain = nas
      Domain = nas.internal
    insertafter: '^\[General\]'

- name: Ensure /etc/idmapd.conf is configured for NFSv4
  lineinfile:
    path: /etc/idmapd.conf
    regexp: '^{{ item.key }}'
    line: "{{ item.key }} = {{ item.value }}"
    state: present
  loop:
    - { key: 'Nobody-User', value: 'nobody' }
    - { key: 'Nobody-Group', value: 'nogroup' }

- name: Flush handlers    # Triggers handlers instantly
  ansible.builtin.meta: flush_handlers
