- name: Export Bitwarden access kry for APPS project
  tags:
    - bw
    - bitwarden
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: 'export BWS_ACCESS_TOKEN="{{ BWS_ACCESS_TOKEN_APPS }}"'
    create: yes
  become: true

- name: Ensure /root/.bashrc sources /secrets/.env if it exists
  tags:
    - bw
    - bitwarden
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: '[[ -f /secrets/.env ]] && source /secrets/.env'
    create: yes
    state: present
    insertafter: EOF
  become: true

- name: Install fetch_bw.sh script
  tags:
    - bw
    - bitwarden
  ansible.builtin.template:
    src: fetch_bw.j2
    dest: /root/fetch_bw.sh
    owner: root
    group: root
    mode: '0700'

- name: Ensure /secrets directory exists
  tags:
    - bw
    - bitwarden
  ansible.builtin.file:
    path: /secrets
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: true

- name: Setup cron job at reboot
  tags:
    - bw
    - bitwarden
  ansible.builtin.cron:
    name: "Fetch Bitwarden secrets at reboot"
    user: root
    special_time: reboot
    job: "/root/fetch_bw.sh"
  become: true

- name: Setup cron job to fetch Bitwarden secrets every 30 minutes
  tags:
    - bw
    - bitwarden
  ansible.builtin.cron:
    name: "Fetch Bitwarden secrets"
    user: root
    minute: "*/15"
    job: ". /root/.bashrc && /usr/bin/env bash /root/fetch_bw.sh >> /var/log/fetch_bw.log 2>&1"
    state: present
  become: true
