---
- name: Notebook - Disable sleep when lid closed
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^(.*)HandleLidSwitch=suspend$'
    line: 'HandleLidSwitch=ignore'
    backrefs: true
    backup: true

- name: Notebook - Restart systemd-logind service
  ansible.builtin.service:
    name: systemd-logind
    state: restarted
