---
- name: Copy DDNS update script
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/update_cloudflare_ddns.sh"
    owner: root
    group: "{{ admin_group[0].name }}"
    mode: '0740'
  loop: 
    - ../templates/update_cloudflare_ddns.j2

- name: Set crontab DDNS update
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    user: "{{ item.user }}"
    job: "{{ item.job }}"
    state: "{{ item.state }}"
  loop:
    - name: "DDNS Cloudflare update"
      minute: "*/20"
      hour: "*"
      user: root
      job: "/bin/bash /update_cloudflare_ddns.sh >> /var/log/cloudflare_ddns.log 2>&1"
      state: present
