---
- name: Find DDNS configuration files
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/roles/ddns/templates/"
  register: config_files
  delegate_to: localhost

- name: Copy DDNS update script
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/{{ item | basename | regex_replace('\\.j2$', '.sh') }}"
    owner: root
    group: "{{ admin_group[0].name }}"
    mode: '0770'
  loop: "{{ config_files.files | map(attribute='path') | list }}"

- name: Set crontab DDNS update
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    user: "{{ item.user }}"
    job: "{{ item.job }}"
    state: "{{ item.state }}"
  loop:
    - name: "DDNS Cloudflare update"
      minute: "*/20"
      hour: "*"
      user: root
      job: "/bin/bash /update_cloudflare_ddns.sh >> /var/log/cloudflare_ddns.log 2>&1"
      state: present
    - name: "DDNS Dynu update"
      minute: "*/10"
      hour: "*"
      user: root
      job: "/bin/bash /update_dynu_ddns.sh >> /var/log/dynu_ddns.log 2>&1"
      state: present
