---
- name: Create Traefik dirs
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ os_username }}"
    group: "{{ item.group }}"
    mode: '0770'
  with_items:
    - path: "{{ tooling_dirs[0].path }}/traefik"
      owner: "{{ os_username }}"
      group: "{{ admin_group[0].name }}"
      mode: '0770'
    - path: /etc/traefik
      owner: "{{ os_username }}"
      group: "{{ admin_group[0].name }}"
      mode: '0770'
    - path: "{{ tools.traefik.log_dir }}"
      owner: root
      group: "{{ admin_group[0].name }}"
      mode: '0750'
- name: Copy Traefik config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: ../templates/traefik.j2
      dest: "{{ tooling_dirs[0].path }}/traefik/docker-compose.yml"
      mode: '0750'
    - src: ../templates/traefik.yml
      dest: /etc/traefik/traefik.yml
      mode: '0750'
  register: config_files
- name: Setup DDNS provider auth variables
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: DYNU_API_KEY={{ tools.traefik.dynu_api_key  }}
- name: Start Traefik
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/traefik"
  when: config_files.changed
- name: Get {{ tools.traefik.container_name }} container info
  docker_container_info:
    name: "{{ tools.traefik.container_name }}"
  register: result
- name: Print the status of the {{ tools.traefik.container_name }} container
  debug:
    msg: |
      Traefik state: {{ result.container['State']['Status'] }}
  when: result.exists
