---
- name: Create dirs - {{ tools.qbittorrent.container_name | upper }}
  ansible.builtin.file:
    state: directory
    path: "{{ tooling_dirs[0].path }}/qbittorrent"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0770'

- name: Copy compose - {{ tools.qbittorrent.container_name | upper }}
  ansible.builtin.template:
    src: "{{ role_path }}/templates/qbittorrent.j2"
    dest: "{{ tooling_dirs[0].path }}/qbittorrent/docker-compose.yml"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: '0750'
  register: compose

- name: Start {{ tools.qbittorrent.container_name | upper }}
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/qbittorrent"
  changed_when: false

# - name: Display container info - {{ tools.qbittorrent.container_name | upper }}
#   ansible.builtin.include_tasks: "../tests/container_info.yml"
#   with_items:
#     - name: "{{ tools.qbittorrent.container_name }}"
#       http_endpoint: http://localhost:8090
#   when: not ansible_check_mode
