- name: Install SSH private key for root
  copy:
    content: "{{ SRV_PRIVATE_KEY | b64decode }}"
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: '0600'
  no_log: true

- name: Clone DockerComposeStack repository
  become_user: "root"
  git:
    repo: "git@github.com:przemekgorzynski/DockerComposeStack.git"
    dest: "/DockerComposeStack"
    version: main
    accept_hostkey: yes
    key_file: "/root/.ssh/id_rsa"
    update: yes
    force: yes

- name: Ensure cronjob runs home lab stack updater every 5 minutes
  cron:
    name: "Update Home Lab Docker stack"
    minute: "*/5"
    job: "/DockerComposeStack/up.sh >> /var/log/home_lab_up.log 2>&1"
    user: root
