---
name: Lint-Ansible
run-name: Commit on branch ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  Ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29   # v4
      - name: Install Ansible && dependencies
        run: |
          sudo apt update
          sudo apt install ansible -y
          ansible --version
          ansible-galaxy collection install -r requirments.yml
      - name: Install Ansible-lint
        run: pip3 install ansible-lint
      - name: Execute Ansible-lint
        run: ansible-lint
