---
name: Dry-run
run-name: Commit on branch ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  Dry-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y
          ansible --version
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          docker --version
      - name: Install Ansible-Galaxy requirements
        run: |
          ansible-galaxy collection install -r requirments.yml
      - name: Deploy Dry-Run playbook
        run: |
          ansible-playbook -i inventory.yml tests/playbook_dry_run.yml
      - name: Execute Testing playbook
        run: |
          ansible-playbook -i inventory.yml tests/playbook_test.yml
      - name: Run tmate   # Allows ssh to machine
        uses: mxschmitt/action-tmate@v3
        if: failure()
