---
- name: Create dirs - {{ tools.traefik.container_name | upper }}
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ os_username }}"
    group: "{{ item.group }}"
    mode: '0770'
  with_items:
    - path: "{{ tooling_dirs[0].path }}/traefik"
      owner: "{{ os_username }}"
      group: "{{ admin_group[0].name }}"
      mode: '0770'
    - path: /etc/traefik
      owner: "{{ os_username }}"
      group: "{{ admin_group[0].name }}"
      mode: '0770'
    - path: "{{ tools.traefik.log_dir }}"
      owner: root
      group: "{{ admin_group[0].name }}"
      mode: '0750'

- name: Copy compose - {{ tools.traefik.container_name | upper }}
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ os_username }}"
    group: "{{ admin_group[0].name }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "{{ role_path }}/templates/traefik.j2"
      dest: "{{ tooling_dirs[0].path }}/traefik/docker-compose.yml"
      mode: '0750'
    - src: "{{ role_path }}/templates/traefik_config.j2"
      dest: /etc/traefik/traefik.yml
      mode: '0750'
  register: config_files

- name: Setup DDNS provider auth variables
  ansible.builtin.blockinfile:
    path: /etc/environment
    block: |
      # AUTH VARIABLES FOR TRAEFIK DDNS CHALLANGE PROVIDERS
      # https://doc.traefik.io/traefik/https/acme/#providers
      CF_API_EMAIL={{ tools.traefik.cloudflare_email }}   # Cloudflare
      CF_API_KEY={{ tools.traefik.cloudflare_api_key }}
      DYNU_API_KEY={{ tools.traefik.dynu_api_key }}       # Dynu

- name: Start {{ tools.traefik.container_name | upper }}
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: "{{ tooling_dirs[0].path }}/traefik"
  changed_when: false

- name: Display container info - {{ tools.traefik.container_name | upper }}
  ansible.builtin.include_tasks: "../tests/container_info.yml"
  with_items:
    - name: "{{ tools.traefik.container_name }}"
      http_endpoint: http://localhost:8080/api/rawdata
  when: not ansible_check_mode
